import assert from 'node:assert/strict';
import { blank, spelling, isCorrect, QType } from '../js/learn-engine.js';
import { schedule, due, exercises } from '../js/guided-plan.js';
const entry = { w: 'ice cream', c: '冰淇淋', e: 'Ice cream is cold. I like ice cream.' };
assert.equal(blank('The theater', 'the'), ' ______  theater');
assert.equal(blank('Art is part of life; art matters.', 'art'), ' ______  is part of life;  ______  matters.');
assert.equal((spelling(entry).example.match(/______/g) || []).length, 2);
assert(isCorrect(spelling(entry), ' ICE   CREAM '));
assert(!isCorrect(spelling(entry), 'icecream'));
assert(isCorrect(spelling({ w: "don't" }), 'DON’T'));
assert(!isCorrect(spelling(entry), ''));
assert(!isCorrect({ type: QType.MEANING_TO_WORD, correctIndex: 1 }, '1'));
const now = Date.parse('2026-09-18T01:00:00Z');
const keys = Array.from({ length: 100 }, (_, i) => String(i));
const one = schedule(keys, '2026-09-18T12:00:00Z', 20, now, 'Asia/Shanghai');
assert.equal(one.days.length, 1); assert.equal(one.days[0].keys.length, 100); assert.equal(one.reviewOnlyLastDay, false);
assert.equal(one.minutes, undefined);
const six = schedule(keys, '2026-09-23T12:00:00Z', 90, now, 'Asia/Shanghai');
assert.equal(six.days.length, 6); assert.equal(six.reviewOnlyLastDay, true); assert.equal(six.days[5].keys.length, 0);
assert.equal(new Set(six.days.flatMap(day => day.keys)).size, 100);
assert.equal(six.estimatedPeakMinutes, undefined);
const tight = schedule(keys, '2026-09-23T12:00:00Z', 60, now, 'Asia/Shanghai');
assert.equal(tight.reviewOnlyLastDay, true);
assert.deepEqual(tight.days, six.days);
const completed = schedule([], '2026-09-23T12:00:00Z', 60, now, 'Asia/Shanghai', keys);
assert.equal(completed.days.flatMap(day => day.keys).length, 0);
assert.equal(completed.days.flatMap(day => day.keys).length, 0);
assert.deepEqual(due(completed, { '0': { complete: true, lastDate: '2026-09-17' }, removed: { complete: true, lastDate: '2026-09-17' } }, now).reviewKeys, ['0']);
assert.throws(() => schedule(['a'], '2026-09-23T12:00:00Z', 60, now, 'Asia/Shanghai', ['a']));
assert.equal(exercises(keys.slice(0, 5)).length, 20);
assert.equal(exercises(['a', 'b'])[2].key, 'a');
assert.throws(() => schedule(keys, 'bad', 20, now));
assert.throws(() => schedule(keys, '2026-09-17T01:00:00Z', 20, now));
const dst = schedule(['a','b','c'], '2026-11-02T18:00:00Z', 20, Date.parse('2026-10-31T16:00:00Z'), 'America/New_York');
assert.equal(dst.days.length, 3);
assert.deepEqual(due(one, { '0': { complete: true, lastDate: '2026-09-17' } }, now).reviewKeys, ['0']);
assert.equal(due(one, {}, now).newKeys.length, 100);
console.log('Learning logic checks passed: spelling, whole-word gaps, one/six-day plans, DST, delayed review.');
